apiVersion: v1
kind: Service
metadata:
  name: frontend-service-http
  namespace: playground
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Use Network Load Balancer
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true" # Uncomment for internal LB
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
